version: 2.1

orbs:
  gradle: circleci/gradle@1.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - gradle/install
      - run:
          name: Build the project
          command: gradle build
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build/classes

  test:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - gradle/install
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: gradle test --tests FilterTests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
