version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - run:
          name: Install Gradle
          command: |
            sudo apt-get update
            sudo apt-get install -y gradle
      - run:
          name: Build the project
          command: gradle build
      - store_artifacts:
          path: out/production/WorkingTruck/test/java/FilterTests.class
      - persist_to_workspace:
          root: .
          paths:
            - out/production/WorkingTruck

  test:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - run:
          name: Install Gradle
          command: |
            sudo apt-get update
            sudo apt-get install -y gradle
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: gradle test --tests src.test.java.FilterTests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
