version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - run:
          name: Install Gradle
          command: |
            sudo apt-get update
            sudo apt-get install -y gradle
      - run:
          name: Build the project
          command: gradle build
  test:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - run:
          name: Install Gradle
          command: |
            sudo apt-get update
            sudo apt-get install -y gradle
      - run:
          name: Build the project
          command: gradle test

workflows:
  build:
    jobs:
      - build