# This is a sample configuration file for building a Maven-based Java project

# Define the version of the pipeline
version: 1.0

# Define the language and environment for your project
language: java
jdk: zulu-19

# Define the build pipeline stages
stages:
  - build

# Define the build job
build:
  stage: build
  script:
    - mvn clean install -DskipTests=true
  artifacts:
    paths:
      - target/*.jar