version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          name: Install Gradle
          command: |
            sudo apt-get update
            sudo apt-get install -y gradle
      - run:
          name: Build the project
          command: gradle build
      - store_artifacts:
          path: build/reports/tests/test/index.html
      - persist_to_workspace:
          root: .
          paths:
            - build/reports/tests/test/index.html

  test:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/my-project
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: gradle test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
