version: 2.1
jobs:
  build:
    docker:
      - image: azul/zulu-openjdk:19
    working_directory: ~/repo
    steps:
      - checkout
      - run:
            name: Install Maven
            command: apt-get update && apt-get install -y maven
      - run:
          name: Install OpenJFX
          command: apt-get update && apt-get install -y openjfx
      - run:
          name: Build the project
          command: mvn build

  test:
    docker:
      - image: azul/zulu-openjdk:19
    working_directory: ~/repo
    steps:
      - checkout
      - run:
            name: Install Maven
            command: apt-get update && apt-get install -y maven
      - run:
          name: Install OpenJFX
          command: apt-get update && apt-get install -y openjfx
      - run:
          name: Run unit tests
          command: mvn test
