version: 2.1

orbs:
  java: circleci/openjdk@1.2.2

jobs:
  build:
    working_directory: ~/trucker-system
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - java/setup-jdk
      - run: ./gradlew build
      - store_artifacts:
          path: build/libs/*.jar
          destination: jars

workflows:
  version: 2
  build:
    jobs:
      - build