version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}
      - run:
          name: Build the project
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target

  test:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    working_directory: ~/trucker-system
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: maven-{{ checksum "pom.xml" }}
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
